---
title: "Boston Water Fountain Locations"
author: "Julia Vasta"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
```

## Load packages

```{r packages, message=FALSE}

library(googlesheets4)
library(sf)
library(leaflet)
library(stringr)
library(dplyr)
library(tidyr)
library(lubridate)
library(sf)
```

## Read data

Read in data from Google Sheet.

```{r read_data, message=FALSE}

df <- read_sheet("https://docs.google.com/spreadsheets/d/1KuzKNWn-ZxbhKwkdaj1CnzyqsKN6Pxm1HxoNpTqErhM/edit?resourcekey=&gid=729659319#gid=729659319")
```

## Transform data

```{r transform}

## Rename columns
df <- 
    df %>%
    rename("timestamp" = 1, "coords" = 2, "fountain_name" = 3, "is_working" = 4, "descr" = 5, "photo" = 6, "submitter_name" = 7)

## Convert timestamp column to date-time object
df$timestamp <- df$timestamp %>%
    ymd_hms()

## Split coordinates into x and y columns
df <- df %>%
    separate(coords, into = c("lat", "long"), sep = ", ", convert = TRUE)

head(df)
```

## Prep for mapping

```{r create_sf_object, warning=FALSE}

## Create sf object out of df
points <- st_as_sf(df, coords = c("long","lat"))

## Set coordinate system to WGS84
st_crs(points$geometry) <- 4326
print(st_crs(points$geometry))

## Write to shapefile
# st_write(points, "fountains.shp")
```

## Map fountains

```{r, fountains_import}

## Import the shapefile we created
shp_fountains <- read_sf("fountains.shp")
```

```{r}
## Browse the basemap options
names(providers)
```


```{r, map}

basemap <- leaflet() %>%
  # add different provider tiles
  addProviderTiles(
    "OpenStreetMap",
    # give the layer a name
    group = "OpenStreetMap"
  ) %>%
  addProviderTiles(
    "Stamen.Toner",
    group = "Stamen.Toner"
  ) %>%
  addProviderTiles(
    "Stamen.Terrain",
    group = "Stamen.Terrain"
  ) %>%
  addProviderTiles(
    "Esri.WorldStreetMap",
    group = "Esri.WorldStreetMap"
  ) %>%
  addProviderTiles(
    "Wikimedia",
    group = "Wikimedia"
  ) %>%
  addProviderTiles(
    "CartoDB.Positron",
    group = "CartoDB.Positron"
  ) %>%
  addProviderTiles(
    "Esri.WorldImagery",
    group = "Esri.WorldImagery"
  ) %>%
# add a layers control
  addLayersControl(
    baseGroups = c(
      "OpenStreetMap", "Stamen.Toner",
      "Stamen.Terrain", "Esri.WorldStreetMap",
      "Wikimedia", "CartoDB.Positron", "Esri.WorldImagery"
    ),
    # position it on the topleft
    position = "topleft"
  )
```

```{r}
leaflet(shp_fountains) %>%
    addProviderTiles("CartoDB.Positron") %>%
    # addProviderTiles("OpenStreetMap") %>%
    addMarkers(popup = ~fntn_nm) %>%
    addCircles()
```


